
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    networks:
      - net-dwh
    ports:
      - "3306:3306"
    volumes:
      - vol-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: CorsiDocker2026
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: CorsiDocker2026

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    networks:
      - net-dwh
    ports:
      - "27017:27017"
    volumes:
      - vol-mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: CorsiDocker2026
      MONGO_INITDB_DATABASE: testdb

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    restart: unless-stopped
    networks:
      - net-dwh
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: CorsiDocker2026

volumes:
  vol-mysql-data:
  vol-mongodb-data:

networks:
  net-dwh:
    driver: bridge
