
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    networks:
      - net-dwh
    ports:
      - "3306:3306"
    volumes:
      - vol-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: CorsiDocker2026
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: CorsiDocker2026

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    networks:
      - net-dwh
    ports:
      - "27017:27017"
    volumes:
      - vol-mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: CorsiDocker2026
      MONGO_INITDB_DATABASE: testdb

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    restart: unless-stopped
    networks:
      - net-dwh
    ports:
      - "8080:8080"
      #- "8443:8443"
    environment:
      # NIFI_WEB_HTTP_PORT: 8080
      # NIFI_WEB_HTTP_HOST: 0.0.0.0
      # NIFI_WEB_HTTPS_HOST: 0.0.0.0
      # SINGLE_USER_CREDENTIALS_USERNAME: admin
      # SINGLE_USER_CREDENTIALS_PASSWORD: CorsiDocker2026
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER=single-user-provider
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=CorsiDocker2026
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs

volumes:
  vol-mysql-data:
  vol-mongodb-data:

  nifi_conf:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_state:
  nifi_logs:

networks:
  net-dwh:
    driver: bridge

